{
 "title": "Dynamic4 Telemetry",
 "description": "Демонстрация работы всей цепочки: генерация → сбор → хранение → визуализация\nПроверка корректности сигналов и тревог\nОтладка модели генерации (dynamic4.c)\nПодготовка к подключению ML-моделей или предиктивной аналитике",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "select ts, pressure from sensor_data2 order by ts;"
    }
   ]
  },
  {
   "title": "Bearing Alarm",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select vibration_alarm from sensor_data2 ORDER BY ts;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select ts,temperature from sensor_data2 order by ts;"
    }
   ]
  },
  {
   "title": "Bearing Vibration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "rawSql": "select ts,vibration from sensor_data2 order by ts;"
    }
   ]
  }
 ]
}